### PR TITLE
Make one-wire pin non-static

### PR DESCRIPTION
**Pull request by mhaas**
I believe this was one of your issues? The following should work - at least, it compiles. Platform.io is pretty cool, btw, I just tried it because of your code.

### CODE REVIEW

**Comment by gordonthree** [comment]
Would that limit the scope for OneWire to exist only inside the function Setup()? Maybe it doesn't matter, since DallasTemperature was declared globally, once it's passed the address of the OneWire connection, it will persist outside of Setup()?

I will compile and upload to real hardware and find out.

Thank you for your help.

**Comment by gordonthree** [comment]
It compiles clean, but does not work. Attempting to read the ds18b20 returns -127.0 which I think indicates the sensor was not found.  I also tested setting OWDAT manually just before calling OneWire oneWire(OWDAT), but that did not help.

**Comment by mhaas** [comment]
Did you get it to work? I saw you modified the Onewire lib?

**Comment by gordonthree** [comment]
Yes, it is working now!

I added a begin method to OneWire along with your suggestion of declaring the ds18b20 class in globals and then defining it in Setup() after OneWire is connected. The changes should be part of the master branch now. 

I have not had a chance to look at your suggestion regarding the adc_mode macro. That will be the last piece of a fully software-configured node firmware, at least for my projects :)

**Pull request merged**
